config/routes.rb
Rails.application.routes.draw do
  resources :onlinesurveys
  resources :mysurveys
  resources :surveys
  root 'onlinesurveys#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mysurvey.rb
class Mysurvey < ApplicationRecord
end

app/models/onlinesurvey.rb
class Onlinesurvey < ApplicationRecord
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mysurveys_controller.rb
class MysurveysController < ApplicationController
  before_action :set_mysurvey, only: %i[ show edit update destroy ]

  # GET /mysurveys or /mysurveys.json
  def index
    @mysurveys = Mysurvey.all
  end

  # GET /mysurveys/1 or /mysurveys/1.json
  def show
  end

  # GET /mysurveys/new
  def new
    @mysurvey = Mysurvey.new
  end

  # GET /mysurveys/1/edit
  def edit
  end

  # POST /mysurveys or /mysurveys.json
  def create
    @mysurvey = Mysurvey.new(mysurvey_params)

    respond_to do |format|
      if @mysurvey.save
        format.html { redirect_to @mysurvey, notice: "Mysurvey was successfully created." }
        format.json { render :show, status: :created, location: @mysurvey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mysurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mysurveys/1 or /mysurveys/1.json
  def update
    respond_to do |format|
      if @mysurvey.update(mysurvey_params)
        format.html { redirect_to @mysurvey, notice: "Mysurvey was successfully updated." }
        format.json { render :show, status: :ok, location: @mysurvey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mysurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mysurveys/1 or /mysurveys/1.json
  def destroy
    @mysurvey.destroy
    respond_to do |format|
      format.html { redirect_to mysurveys_url, notice: "Mysurvey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mysurvey
      @mysurvey = Mysurvey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mysurvey_params
      params.require(:mysurvey).permit(:name, :laptop, :type)
    end
end

app/controllers/onlinesurveys_controller.rb
class OnlinesurveysController < ApplicationController
  before_action :set_onlinesurvey, only: %i[ show edit update destroy ]

  # GET /onlinesurveys or /onlinesurveys.json
  def index
    @onlinesurveys = Onlinesurvey.all
  end

  # GET /onlinesurveys/1 or /onlinesurveys/1.json
  def show
  end

  # GET /onlinesurveys/new
  def new
    @onlinesurvey = Onlinesurvey.new
  end

  # GET /onlinesurveys/1/edit
  def edit
  end

  # POST /onlinesurveys or /onlinesurveys.json
  def create
    @onlinesurvey = Onlinesurvey.new(onlinesurvey_params)

    respond_to do |format|
      if @onlinesurvey.save
        format.html { redirect_to @onlinesurvey, notice: "Onlinesurvey was successfully created." }
        format.json { render :show, status: :created, location: @onlinesurvey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @onlinesurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onlinesurveys/1 or /onlinesurveys/1.json
  def update
    respond_to do |format|
      if @onlinesurvey.update(onlinesurvey_params)
        format.html { redirect_to @onlinesurvey, notice: "Onlinesurvey was successfully updated." }
        format.json { render :show, status: :ok, location: @onlinesurvey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @onlinesurvey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onlinesurveys/1 or /onlinesurveys/1.json
  def destroy
    @onlinesurvey.destroy
    respond_to do |format|
      format.html { redirect_to onlinesurveys_url, notice: "Onlinesurvey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_onlinesurvey
      @onlinesurvey = Onlinesurvey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def onlinesurvey_params
      params.require(:onlinesurvey).permit(:name, :laptop, :manufacturer)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.fetch(:survey, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mysurveys_helper.rb
module MysurveysHelper
end

app/helpers/onlinesurveys_helper.rb
module OnlinesurveysHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Surveyapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mysurveys/_form.html.erb
<%= form_with(model: mysurvey) do |form| %>
  <% if mysurvey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mysurvey.errors.count, "error") %> prohibited this mysurvey from being saved:</h2>

      <ul>
        <% mysurvey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :laptop %>
    <%= form.text_field :laptop %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mysurveys/edit.html.erb
<h1>Editing Mysurvey</h1>

<%= render 'form', mysurvey: @mysurvey %>

<%= link_to 'Show', @mysurvey %> |
<%= link_to 'Back', mysurveys_path %>

app/views/mysurveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mysurveys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Laptop</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mysurveys.each do |mysurvey| %>
      <tr>
        <td><%= mysurvey.name %></td>
        <td><%= mysurvey.laptop %></td>
        <td><%= mysurvey.type %></td>
        <td><%= link_to 'Show', mysurvey %></td>
        <td><%= link_to 'Edit', edit_mysurvey_path(mysurvey) %></td>
        <td><%= link_to 'Destroy', mysurvey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mysurvey', new_mysurvey_path %>

app/views/mysurveys/new.html.erb
<h1>New Mysurvey</h1>

<%= render 'form', mysurvey: @mysurvey %>

<%= link_to 'Back', mysurveys_path %>

app/views/mysurveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mysurvey.name %>
</p>

<p>
  <strong>Laptop:</strong>
  <%= @mysurvey.laptop %>
</p>

<p>
  <strong>Type:</strong>
  <%= @mysurvey.type %>
</p>

<%= link_to 'Edit', edit_mysurvey_path(@mysurvey) %> |
<%= link_to 'Back', mysurveys_path %>

app/views/onlinesurveys/_form.html.erb
<%= form_with(model: onlinesurvey) do |form| %>
  <% if onlinesurvey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(onlinesurvey.errors.count, "error") %> prohibited this onlinesurvey from being saved:</h2>

      <ul>
        <% onlinesurvey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Enter your Name:" %><br/>
    <%= form.text_field :name, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :laptop, "Do you own a laptop?" %><br />
    <%= form.radio_button :laptop, 'Yes', class:"form-check-input"%>
	<%= form.label :laptop, "Yes", :value => "true"%><br/>
    <%= form.radio_button :laptop, 'No', :checked => true%>
	<%= form.label :laptop, "No", :value => "false" %>
  </div>

  <div class="form-group">
  <%= form.label :laptop, "Which type of laptop?" %><br />
     <%= form.select :manufacturer, ['No laptop','Taifa','HP', 'Lenovo','MacBook', 'Acer','Asus'],{},{ class: "form form-group form-control" } %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit response",class:"btn btn-primary" %>
  </div>
<% end %>

app/views/onlinesurveys/edit.html.erb
<div class = "container" style="border:1px solid #cecece; border-radius:5px; margin-top:30px; width:500px; padding:30px; box-shadow: 1px 3px 4px 1px rgba(230,222,222,0.75);">
<h1>Editing laptop survey</h1>

<%= render 'form', onlinesurvey: @onlinesurvey %>

<%= link_to 'Show', @onlinesurvey %> |
<%= link_to 'Back', onlinesurveys_path %>
</div>

app/views/onlinesurveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>SURVEY RESPONSES</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Laptop</th>
      <th>Manufacturer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @onlinesurveys.each do |onlinesurvey| %>
      <tr>
        <td><%= onlinesurvey.name %></td>
        <td><%= onlinesurvey.laptop %></td>
        <td><%= onlinesurvey.manufacturer %></td>
        <td><%= link_to 'Show', onlinesurvey %></td>
        <td><%= link_to 'Edit', edit_onlinesurvey_path(onlinesurvey) %></td>
        <td><%= link_to 'Destroy', onlinesurvey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New survey form', new_onlinesurvey_path %>

app/views/onlinesurveys/new.html.erb
<div class = "container" style="border:1px solid #cecece; border-radius:5px; margin-top:60px; width:500px; padding:30px; box-shadow: 1px 3px 4px 1px rgba(230,222,222,0.75);">
<div class="col align-items-center justify-content-center">
    
<h3>VERONICA WEFITSA JUMA</h3>
<h3>SCT222-0395/2017</h3>
<h1>SURVEY ON LAPTOPS</h1>

<%= render 'form', onlinesurvey: @onlinesurvey %>

<%= link_to 'Back', onlinesurveys_path %>
</div>
</div>

app/views/onlinesurveys/show.html.erb
<div class = "container" style="border:1px solid #cecece; border-radius:5px; margin-top:30px; width:500px; padding:30px; box-shadow: 1px 3px 4px 1px rgba(230,222,222,0.75);">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @onlinesurvey.name %>
</p>

<p>
  <strong>Laptop:</strong>
  <%= @onlinesurvey.laptop %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @onlinesurvey.manufacturer %>
</p>

<%= link_to 'Edit', edit_onlinesurvey_path(@onlinesurvey) %> |
<%= link_to 'Back', onlinesurveys_path %>
</div>

app/views/surveys/_form.html.erb
<%= form_with(model: survey) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>